services:
  - type: web
    name: sql-assistant-api
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --use-pep517 --only-binary=:all: -r requirements.txt
    startCommand: uvicorn sql_assistant_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PIP_ONLY_BINARY
        value: ":all:"
      - key: PIP_PREFER_BINARY
        value: "1"
