services:
  - type: web
    name: sql-assistant-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn sql_assistant_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
